blank_issues_enabled: false
contact_links:
  - name: ğŸ”– å…³æ³¨ä¸­å›½DevOpsç¤¾åŒºå®˜ç½‘ 
    url: https://DevOpsChina.org
    about: è®¿é—®ç¤¾åŒºå®˜ç½‘äº†è§£â€œDevOpså·¥å…·é‰´å®â€æ´»åŠ¨è¯¦æƒ… ğŸŒ
  - name: ğŸ”– å…³æ³¨ç¤¾åŒºå¾®ä¿¡å…¬ä¼—å·
    url: https://mp.weixin.qq.com/s/__h3SpSNMdZ0LzsDEWV83A
    about: ä¸ç¤¾åŒºä¿æŒå¯†åˆ‡è”ç³» ğŸŒ